name: Ase
version: '${version}'
main: com.github.jenya705.ase.AsePlugin
api-version: 1.18
authors: [ Jenya705 ]
description: Armor Stand Editor for Paper servers
commands:
  ase:
    permission: ase.ase
    description: Ase main command
    usage: /ase <give> [...]
permissions:
  ase.*:
    default: op
    children:
      ase.ase: true
  ase.ase:
    default: op